// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public class Cart
{
    public int CartID { get; set; }

    public int CustomerID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Products Product { get; set; }
}