// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class Match
{
    public int MatchID { get; set; }

    public string MatchName { get; set; }

    public int HomeTeamID { get; set; }

    public int GuestTeamID { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Stadium { get; set; }

    public int? HomeTeamScore { get; set; }

    public int? GuestTeamScore { get; set; }

    public int CompetitionID { get; set; }

    public string Description { get; set; }

    public virtual Competition Competition { get; set; }

    public virtual Team GuestTeam { get; set; }

    public virtual Team HomeTeam { get; set; }
}