// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public class OrderContent
{
    public int OrderContentID { get; set; }

    public int OrderID { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    public double? Price { get; set; }

    public virtual Orders Order { get; set; }

    public virtual Products Product { get; set; }
}