// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class Products
{
    public int ProductID { get; set; }

    public string ProductName { get; set; }

    public string Description { get; set; }

    public int? CategoryID { get; set; }

    public double? Price { get; set; }

    public int? InStock { get; set; }

    public int? OnOrder { get; set; }

    public int Discontinued { get; set; }

    public int TeamID { get; set; }

    public int? PlayerID { get; set; }

    public virtual ICollection<Cart> Cart { get; set; } = new List<Cart>();

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderContent> OrderContent { get; set; } = new List<OrderContent>();

    public virtual Player Player { get; set; }

    public virtual ICollection<ProductImage> ProductImage { get; set; } = new List<ProductImage>();

    public virtual Team Team { get; set; }
}