// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models;

public partial class TeamPlayerHistory
{
    public int ID { get; set; }

    public int TeamID { get; set; }

    public int PlayerID { get; set; }

    public DateTime JoinDate { get; set; }

    public DateTime? LeaveDate { get; set; }

    public virtual Player Player { get; set; }

    public virtual Team Team { get; set; }
}