//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int MatchID { get; set; }
        public string MatchName { get; set; }
        public int HomeTeamID { get; set; }
        public int GuestTeamID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Stadium { get; set; }
        public Nullable<int> HomeTeamScore { get; set; }
        public Nullable<int> GuestTeamScore { get; set; }
        public int CompetitionID { get; set; }
        public string Description { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
