//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderContents = new HashSet<OrderContent>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public int AddressID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public string Expire { get; set; }
        public Nullable<int> SecurityCode { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderContent> OrderContents { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Status Status { get; set; }
    }
}
