//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerImage
    {
        public int PlayerImageID { get; set; }
        public int PlayerID { get; set; }
        public string ImageURL { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
