// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class Competition
    {
        public Competition()
        {
            Match = new HashSet<Match>();
        }

        public int CompetitionId { get; set; }
        public string CompetitionName { get; set; }

        public virtual ICollection<Match> Match { get; set; }
    }
}