// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class Employee
    {
        public Employee()
        {
            News = new HashSet<News>();
            Orders = new HashSet<Orders>();
        }

        public int EmployeeId { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }

        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}