// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models;

public partial class News
{
    public int NewsID { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public string Contents { get; set; }

    public string ImageURL { get; set; }

    public int? EmployeeID { get; set; }

    public virtual Employee Employee { get; set; }
}