// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class OrderContent
    {
        public int OrderContentId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public double? Price { get; set; }

        public virtual Orders Order { get; set; }
        public virtual Products Product { get; set; }
    }
}