// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            Orders = new HashSet<Orders>();
        }

        public int PaymentMethodId { get; set; }
        public string PaymentMethod1 { get; set; }

        public virtual ICollection<Orders> Orders { get; set; }
    }
}