// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class Player
    {
        public Player()
        {
            PlayerImage = new HashSet<PlayerImage>();
            PlayerScore = new HashSet<PlayerScore>();
            Products = new HashSet<Products>();
            TeamPlayerHistory = new HashSet<TeamPlayerHistory>();
        }

        public int PlayerId { get; set; }
        public string FullName { get; set; }
        public DateTime Dob { get; set; }
        public string Pob { get; set; }
        public int Height { get; set; }
        public string Position { get; set; }
        public int? CurrentTeam { get; set; }
        public int? Number { get; set; }
        public int? Scores { get; set; }

        public virtual Team CurrentTeamNavigation { get; set; }
        public virtual ICollection<PlayerImage> PlayerImage { get; set; }
        public virtual ICollection<PlayerScore> PlayerScore { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<TeamPlayerHistory> TeamPlayerHistory { get; set; }
    }
}