// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models;

public partial class PlayerScore
{
    public int MatchID { get; set; }

    public int PlayerID { get; set; }

    public int Scores { get; set; }

    public virtual Match Match { get; set; }

    public virtual Player Player { get; set; }
}