// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class PlayerImage
    {
        public int PlayerImageId { get; set; }
        public int PlayerId { get; set; }
        public string ImageUrl { get; set; }

        public virtual Player Player { get; set; }
    }
}