// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models;

public partial class PlayerImage
{
    public int PlayerImageID { get; set; }

    public int PlayerID { get; set; }

    public string ImageURL { get; set; }

    public virtual Player Player { get; set; }
}