// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class ProductImage
    {
        public int ProductImageId { get; set; }
        public int ProductId { get; set; }
        public string ImageUrl { get; set; }

        public virtual Products Product { get; set; }

        public ProductImage()
        {
        }

        public ProductImage(int productImageId, int productId, string imageUrl, Products product)
        {
            ProductImageId = productImageId;
            ProductId = productId;
            ImageUrl = imageUrl;
            Product = product;
        }
    }
}