// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class Products
    {
        public Products()
        {
            Cart = new HashSet<Cart>();
            OrderContent = new HashSet<OrderContent>();
            ProductImage = new HashSet<ProductImage>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int? CategoryId { get; set; }
        public double? Price { get; set; }
        public int? InStock { get; set; }
        public int? OnOrder { get; set; }
        public int Discontinued { get; set; }
        public int TeamId { get; set; }
        public int? PlayerId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Player Player { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<OrderContent> OrderContent { get; set; }
        public virtual ICollection<ProductImage> ProductImage { get; set; }
    }
}