// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SoccerManager.Models
{
    public partial class TeamImage
    {
        public int TeamImageId { get; set; }
        public int TeamId { get; set; }
        public string ImageUrl { get; set; }

        public virtual Team Team { get; set; }
    }
}